server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: PlfkuKaVCVcenFwvxcKDYpxLdVcitpwn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

google:
  client-id: 762142748326-g5nthijmrgrgtqjafp9kvu6dkflu3o6h.apps.googleusercontent.com

jwt:
  secret: mi-secreto-super-seguro-para-produccion-2024
  expiration-ms: 86400000

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000,https://turismo-poc-f40af.web.app

logging:
  level:
    com.turismo: DEBUG
    org.springframework.security: INFO